language: ruby

rvm:
  - ruby-head
  - 3.0
  - 2.7
  - 2.6

jobs:
  allow_failures:
    - ruby: ruby-head
    - ruby: 3.0

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
